import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
import { chromium, devices } from 'playwright';
const VIEWER = path.resolve('viewer'); const OUTD = process.argv[2]; const devName = process.argv[3] || 'iPhone 13';
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.svg': 'image/svg+xml' };
const server = http.createServer((req, res) => { const u = decodeURIComponent(new URL(req.url, 'http://x').pathname); const f = path.join(VIEWER, u === '/' ? 'index.html' : u); if (!fs.existsSync(f) || fs.statSync(f).isDirectory()) { res.writeHead(404); return res.end(); } res.writeHead(200, { 'Content-Type': MIME[path.extname(f)] || 'text/plain' }); fs.createReadStream(f).pipe(res); });
await new Promise((r) => server.listen(0, '127.0.0.1', r));
const base = `http://127.0.0.1:${server.address().port}/`;
const b = await chromium.launch({ args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await b.newContext({ ...devices[devName] });
const p = await ctx.newPage();
p.on('pageerror', (e) => console.log('pageerror', e.message)); p.on('console', (m) => { if (m.type() === 'error') console.log('console', m.text()); });
const shot = async (n) => { await p.waitForTimeout(400); await p.screenshot({ path: path.join(OUTD, `${devName.replace(/\W/g, '')}-${n}.png`) }); };
await p.goto(base); await p.waitForFunction(() => document.getElementById('loading').style.display === 'none');
console.log('viewport', p.viewportSize());
await shot('01-load');
await p.locator('#introClose').tap();
// toolbar layout
const tb = await p.evaluate(() => [...document.querySelectorAll('#toolbar button, #sidebarToggle')].map((b) => { const r = b.getBoundingClientRect(); return [b.textContent.trim(), Math.round(r.x), Math.round(r.y), Math.round(r.width), Math.round(r.height)]; }));
console.log('toolbar', JSON.stringify(tb));
await p.locator('#clList .row', { hasText: 'Leg Rear' }).first().tap();
await shot('02-selected-from-list');
// tap on model center
const vp = await p.locator('#viewport').boundingBox();
await p.touchscreen.tap(vp.x + vp.width / 2, vp.y + vp.height / 2);
await shot('03-tap-model');
await p.locator('#measureAngleBtn').tap();
await shot('04-angle-tool');
await p.locator('#measureAngleBtn').tap();
await p.locator('#helpBtn').tap();
await shot('05-help');
await p.locator('#helpClose').tap();
await p.locator('#clDiagram').tap();
await shot('06-diagram');
await p.locator('#diagram .cd-close').tap();
await p.locator('#clLibrary').tap();
await shot('07-library');
await p.locator('#library .lib-close').tap();
await p.locator('#sidebarToggle').tap();
await shot('08-sidebar-toggle');
await b.close(); server.close();
